# Generated by Django 5.1.1 on 2024-09-28 12:30

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mother',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='age',
        ),
        migrations.AddField(
            model_name='mother',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 12, 30, 20, 500310, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='last_checkup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mother',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2024, 9, 28, 12, 30, 57, 513070, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='health.mother'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='health.mother'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
