# Generated by Django 5.1.1 on 2024-09-28 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_rename_name_mother_first_name_remove_mother_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 28, 13, 28, 49, 685316, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mother',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 28, 13, 29, 3, 572982, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
