# Generated by Django 5.1.1 on 2024-09-28 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_child_registration_date_mother_registration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='child',
            name='name',
        ),
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2024, 9, 28, 13, 52, 49, 597666, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2024, 9, 28, 13, 53, 2, 95627, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
